export const SPRITE_CANVAS_VIEWPORT = {
  MIN_ZOOM: 0.1,
  MAX_ZOOM: 5,
  WHEEL_ZOOM_FACTOR: 0.03,
} as const;

export const SPRITE_PREVIEW_VIEWPORT = {
  MIN_ZOOM: 0.1,
  MAX_ZOOM: 20,
  WHEEL_ZOOM_FACTOR: 0.1,
  ZOOM_STEP_IN: 1.25,
  ZOOM_STEP_OUT: 0.8,
  INITIAL_FRAME_ZOOM: 3,
  INITIAL_ANIM_ZOOM: 2,
} as const;
