"use client";

import { useMemo } from "react";
import { EditorLayersContextValue } from "../contexts";

type UseEditorLayerContextValueOptions = EditorLayersContextValue;

export function useEditorLayerContextValue(
  options: UseEditorLayerContextValueOptions
): EditorLayersContextValue {
  const {
    layers,
    setLayers,
    activeLayerId,
    setActiveLayerId,
    selectedLayerIds,
    setSelectedLayerIds,
    draggedLayerId,
    setDraggedLayerId,
    dragOverLayerId,
    setDragOverLayerId,
    layerCanvasesRef,
    editCanvasRef,
    addPaintLayer,
    addFilterLayer,
    addImageLayer,
    deleteLayer,
    selectLayer,
    toggleLayerVisibility,
    updateLayer,
    updateLayerOpacity,
    updateLayerPosition,
    updateMultipleLayerPositions,
    renameLayer,
    toggleLayerLock,
    moveLayer,
    reorderLayers,
    mergeLayerDown,
    duplicateLayer,
    rotateAllLayerCanvases,
    selectLayerWithModifier,
    clearLayerSelection,
    alignLayers,
    distributeLayers,
    initLayers,
    addLayer,
  } = options;

  return useMemo(
    () => ({
      layers,
      setLayers,
      activeLayerId,
      setActiveLayerId,
      selectedLayerIds,
      setSelectedLayerIds,
      draggedLayerId,
      setDraggedLayerId,
      dragOverLayerId,
      setDragOverLayerId,
      layerCanvasesRef,
      editCanvasRef,
      addPaintLayer,
      addFilterLayer,
      addImageLayer,
      deleteLayer,
      selectLayer,
      toggleLayerVisibility,
      updateLayer,
      updateLayerOpacity,
      updateLayerPosition,
      updateMultipleLayerPositions,
      renameLayer,
      toggleLayerLock,
      moveLayer,
      reorderLayers,
      mergeLayerDown,
      duplicateLayer,
      rotateAllLayerCanvases,
      selectLayerWithModifier,
      clearLayerSelection,
      alignLayers,
      distributeLayers,
      initLayers,
      addLayer,
    }),
    [
      layers,
      setLayers,
      activeLayerId,
      setActiveLayerId,
      selectedLayerIds,
      setSelectedLayerIds,
      draggedLayerId,
      setDraggedLayerId,
      dragOverLayerId,
      setDragOverLayerId,
      layerCanvasesRef,
      editCanvasRef,
      addPaintLayer,
      addFilterLayer,
      addImageLayer,
      deleteLayer,
      selectLayer,
      toggleLayerVisibility,
      updateLayer,
      updateLayerOpacity,
      updateLayerPosition,
      updateMultipleLayerPositions,
      renameLayer,
      toggleLayerLock,
      moveLayer,
      reorderLayers,
      mergeLayerDown,
      duplicateLayer,
      rotateAllLayerCanvases,
      selectLayerWithModifier,
      clearLayerSelection,
      alignLayers,
      distributeLayers,
      initLayers,
      addLayer,
    ]
  );
}
